services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - backend

  devhill:
    build: backend
    restart: on-failure:3
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db1
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - proxy
      - backend

  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - devhill
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
      - ./front:/usr/share/nginx/html:ro
    networks:
      - proxy

  cloudflare-tunnel:
    image: cloudflare/cloudflared
    restart: on-failure:3
    depends_on:
      - nginx
    volumes:
      - ./.cloudflared/config.yml:/etc/cloudflared/config.yml
      - ./.cloudflared/creds.json:/etc/cloudflared/creds.json
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --config /etc/cloudflared/config.yml run --token ${TUNNEL_TOKEN}
    networks:
      - proxy

networks:
  proxy:
  backend:

volumes:
  dbdata: